version: '3'
services:
  logstash:
    image: ci-tool-stack/logstash:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile.${VERSION:-latest}
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - no_proxy=$no_proxy
    environment:
# cf env2yaml
      - pipeline.workers=2
#     volumes:
#      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - 9600:9600
      - 5044:5044
    networks:
      - esnet
networks:
  esnet:
